---
# tasks file for proxy.role
- name: update cache
  apt:
    update_cache: yes
  tags:
    - cache
- name: wget latest deb repo package for zabbix
  get_url:
    url: https://repo.zabbix.com/zabbix/6.1/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.1-1+ubuntu20.04_all.deb
    dest: /home/ubuntu/zabbix.deb
  tags:
    - wget
- name: dpkg
  apt:
    deb: /home/ubuntu/zabbix.deb
  tags:
    - dpkg
- name: update cache deb
  apt:
    update_cache: yes
  tags:
    - cache-deb
- name: Install zabbix packages for agent
  apt:
    name: "{{ zabbix_packages }}"
    state: present
  tags:
    - packages
- name: change zabbix agent hostname suitable to zabbix frontend
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname=Zabbix server'
    line: 'Hostname={{ ansible_hostname }}'
    backup: yes
- name: Start zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
    daemon_reload: yes